name: tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    uses: amineutron/.github/.github/workflows/python-ci.yml@main
    with:
      python-versions: '["3.11", "3.12"]'
      lint: false
